### PR TITLE
┬──┬ ノ( ゜-゜ノ)

### PR DESCRIPTION
**Pull request by moutons**
I am ~not~ good at art things

### CODE REVIEW

**Comment by stevemar** [comment]
decisions, decisions... see #1 also

**Comment by moutons** [comment]
@jjasghar may have been #1 but didn't contribute an original work of "art" 😀

**Comment by jjasghar** [comment]
image

**Comment by jjasghar** [comment]
image

**Comment by moutons** [comment]
I can only assume this is what you meant, @jjasghar

**Review by stevemar — APPROVED** [review]
++

**Comment by jjasghar** [comment]
Beautiful.

**Comment by jjasghar** [comment]
This feels like the best OSS PR discourse that has ever happened.

**Comment by paulczar** [comment]
I like the logo, don't think we need the animated gif as well tho

**Comment by paulczar** [comment]
also please rebase it to a single commit :D

**Review by etoews — COMMENTED** [review]
The cuttleserver image should have 20% more pizzazz.

**Comment by moutons** [comment]
I am not good at art things @everett-toews, someone else will have to update it. @paulczar you know there's a squarsh button on merge now right? Still, I force-updated my remote like @jjasghar's commit never even existed.

**Pull request merged**
